export const quotes = [
  { author: "Japanese Proverb", quote: "Fall seven times and stand up eight." },
  { author: "Chinese Proverb", quote: "The person who says it cannot be done should not interrupt the person who is doing it." },
  { author: "Henry David Thoreau", quote: "Go confidently in the direction of your dreams. Live the life you have imagined." },
  { author: "Erica Jong", quote: "You take your life in your own hands, and what happens? A terrible thing, no one to blame." },
  { author: "Alice Walker", quote: "The most common way people give up their power is by thinking they don't have any." },
  { author: "Dalai Lama", quote: "Happiness is not something readymade. It comes from your own actions." },
  { author: "Marie Curie", quote: "We must believe that we are gifted for something, and that this thing, at whatever cost, must be attained." },
  { author: "Lao Tzu", quote: "When I let go of what I am, I become what I might be." },
  { author: "Socrates", quote: "An unexamined life is not worth living." },
  { author: "Vincent Van Gogh", quote: "If you hear a voice within you say \"you cannot paint,\" then by all means paint and that voice be silenced." },
  { author: "Grandma Moses", quote: "Life is what we make it, always has been, always will be." },
  { author: "Theodore Roosevelt", quote: "Believe you can and you're halfway there." },
  { author: "Maimonides", quote: "Teach thy tongue to say, \"I do not know,\" and thous shalt progress." },
  { author: "Helen Keller", quote: "When one door of happiness closes, another opens, but often we look so long at the closed door that we do not see the one that has been opened for us." },
  { author: "Abraham Lincoln", quote: "It's not the years in your life that count. It's the life in your years." },
  { author: "Kevin Kruse", quote: "Life isn't about getting and having, it's about giving and being." },
  { author: "Latin Proverb", quote: "If the wind will not serve, take to the oars." },
  { author: "Teddy Roosevelt", quote: "Do what you can, where you are, with what you have." },
  { author: "Audrey Hepburn", quote: "Nothing is impossible, the word itself says, \"I'm possible!\"" },
  { author: "Charles Swindoll", quote: "Life is 10% what happens to me and 90% of how I react to it." }, 
  { author: "Eleanor Roosevelt", quote: "Remember no one can make you feel inferior without your consent." },
  { author: "Jesse Ownes", quote: "The battles that count aren't the ones for gold medals. The struggles within yourself-the invisible battles inside all of us- that's where it's at." },
  { author: "Unknown", quote: "You can't fall if you don't climb. But there's no joy in living your whole life on the ground." },
  { author: "Maya Angelou", quote: "Life is not measured by the number of breaths we take, but by the moments that take our breath away." },
  { author: "Leonardo da Vinci", quote: "I have been impressed with the urgency of doing. Knowing is not enough; we must apply. Being willing is not enough; we must do." },
  { author: "Norman Vincent Peale", quote: "Change your thoughts and you change your world." },
  { author: "Pablo Picasso", quote: "Every child is an artist. The problem is how to remain an artist once he grows up." },
  { author: "Abigail Van Buren", quote: "If you want your children to turn out well, spend twice as much time with them, and half as much money." },
  { author: "George Eliot", quote: "It is never too late to be what you might have been." },
  { author: "Maya Angelou", quote: "I've learned that people will forget what you said, people will forget what you did, but people will never forget how you made them feel." },
  { author: "Benjamin Franklin", quote: "Either write something worth reading or do something worth writing." },
  { author: "Ralph Waldo Emerson", quote: "The only person you are destined to become is the person you decide to be." },
  { author: "Benjamin Franklin", quote: "I didn't fail the test. I just found 100 ways to do it wrong." },
  { author: "Farrah Gray", quote: "Build your own dreams, or someone else will hire you to build theirs." },
  { author: "Plato", quote: "We can easily forgive a child who is afraid of the dark; the real tragedy of life is when men are afraid of the light." },
  { author: "Beverly Sills", quote: "You may be disappointed if you fail, but you are doomed if you don't try." }, 
  { author: "Jesus", quote: "Ask and it will be given to you; search, and you will find; knock and the door will be opened for you." }
]; 
